WWSampleProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(pattern_name='course_list')),  # Add a redirect from base URL to Course List page
    url(r'^courses/', include("coursecatalog.urls")),  # Include app coursecatalog's URLconfs:

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Note:  Serving static files like this is only good for development -- NOT PRODUCTION.
# https://docs.djangoproject.com/en/dev/howto/static-files/#serving-files-uploaded-by-a-user-during-development

coursecatalog/urls.py
from django.conf.urls import url
from . import views

# The url() function is passed four arguments, two required: regex and view, and two optional: kwargs, and name

urlpatterns = [
    url(r'^$', views.list_courses, name='course_list'),
    url(r'^add/$', views.course_form, name='add_course'),
    url(r'^(?P<course_id>[0-9]+)/$', views.detail_course, name='detail_course'),
    url(r'^(?P<course_id>[0-9]+)/change/$', views.course_form, name='change_course'),
]

coursecatalog/models.py
from django.db import models
import datetime
# Create your models here.


class Instructor(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Course(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=500)
    # One to one relationship with a single instructor--assuming there can only be one instructor per class.
    instructor = models.ForeignKey(Instructor)

    # Duration Field Options:
    TWOWEEKS = datetime.timedelta(weeks=2)
    EIGHTWEEKS = datetime.timedelta(weeks=8)
    DURATION_CHOICES = (
        (TWOWEEKS, '2 Weeks'),
        (EIGHTWEEKS, '8 Weeks'),
    )
    duration = models.DurationField(choices=DURATION_CHOICES, default=TWOWEEKS)
    course_art = models.ImageField(upload_to='uploads/')  # file will be uploaded to MEDIA_ROOT/uploads

    def __str__(self):
        # Sample string representation:   title: description (instructor)
        return self.title + ": " + self.description + " (" + self.instructor.name + ")"

coursecatalog/forms.py
from django.forms import ModelForm
from django import forms
from .models import Course


class CourseForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Name it something good'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['instructor'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Course

        widgets = {
            'description': forms.Textarea(attrs={'rows': 2}),
            'duration': forms.RadioSelect(),
            # I could not figure out how to style the ImageField to be similar to the picture using forms.
            # I resorted to using a CSS and JavaScript solution.
            # 'course_art': forms.FileInput(attrs={'class': 'btn btn-primary btn-lg'}),
        }

        labels = {
            'title': 'Course Title',
            'description': 'Description',
            'instructor': 'Instructor',
            'duration': 'Course Duration',
            'course_art': 'Art',
        }

        help_texts = {
            'description': 'Provide some information about what students will learn.',
        }

        fields = ['title', 'description', 'instructor', 'duration', 'course_art']

coursecatalog/views.py
from django.shortcuts import render
from .models import *
from .forms import CourseForm
from django.contrib import messages
# Create your views here.


def course_form(request, course_id=None):
    """
    Allows users to add a new course to the course catalog.
    Allows users to modify and update an existing course's details.
    :param course_id: The Pk or Id of the course object to be edited.
    :param request: The Django HttpRequest object
    :return: HttpResponse
    """

    # if this is a POST request we need to process the form data
    if request.method == "POST":
        if course_id:
            # Updating an existing record so get the model instance to be updated
            course = Course.objects.get(pk=course_id)
            # Using _ to avoid shadowing outer scope form variable
            _course_form = CourseForm(request.POST, request.FILES, instance=course)

        else:
            # Creating a new record using blank form populated w/ the post data:
            _course_form = CourseForm(request.POST, request.FILES)

        # If the data is valid, save it and return success, else return failure
        if _course_form.is_valid():
            _course_form.save()
            messages.success(request, 'Course Saved Successfully')
        else:
            messages.error(request, 'Course Save Unsuccessful')

        context = {
            'course_id': course_id,
            'course_form': _course_form,
            'request': request
        }

        return render(request, 'coursecatalog/course_form.html', context)

    # if a GET or any other method, create a form based on if course_id was passed to the view:
    else:
        # Retrieving info on existing item
        if course_id:
            course = Course.objects.get(pk=course_id)
            _course_form = CourseForm(instance=course)

        # Creating new, blank course form
        else:
            _course_form = CourseForm()

        context = {
            'course_id': course_id,
            'course_form': _course_form,
            'request': request
        }

        return render(request, 'coursecatalog/course_form.html', context)


def list_courses(request):
    """
    Lists all current courses in the catalog in an easy to read fashion.
    :param request: The Django HttpRequest object
    :return: HttpResponse
    """

    # Retrieve course list from Course Models:
    course_list = Course.objects.all().order_by('pk')

    context = {'course_list': course_list}

    return render(request, 'coursecatalog/course_list.html', context)


def detail_course(request, course_id):
    """
    Displays all details (i.e., course model values) of a specific course in the catalog in an easy to read fashion.
    :param course_id:  The primary key of the Course to be displayed.
    :param request: The Django HttpRequest object
    :return: HttpResponse
    """

    # Retrieve specific course from Course Models:
    course = Course.objects.get(pk=course_id)

    context = {'course': course}

    return render(request, 'coursecatalog/course_details.html', context)

templates/coursecatalog/course_details.html
{% extends 'coursecatalog/index.html' %}

<title>{% block title %}Course Details{% endblock title %}</title>

{% block content %}

    <div class="container">

        <div class="row">
            <div class="col-md-6">
                <h1 class="larger-h1">
                    {{ course.title }}
                </h1>
            </div>
            <div class="col-md-offset-1 col-md-2 h1-margins">
                <a class="btn btn-primary btn-lg" href="{% url 'change_course' course.id %}">Change</a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h3>{{ course.description }}</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                {# This might need limits, b/c otherwise this scales to the dimensions of the image.  If a user uploads a very large image, this could be an issue. #}
                <img src="{{ course.course_art.url }}" alt="No Image Found"/>
            </div>
            <div class="col-md-6">
                <ul>
                    <li>Instructor: {{ course.instructor }}</li>
                    <li>Duration: {{ course.get_duration_display }}</li>
                </ul>
            </div>
        </div>


    </div>
{% endblock content %}

templates/coursecatalog/course_form.html
{% extends 'coursecatalog/index.html' %}
{% load staticfiles %}

<title>
    {% block title %}
        {% if course_id %}
            Edit Course
        {% else %}
            Add Course
        {% endif %}
    {% endblock title %}
</title>

{% block css %}
    {#The command block.super makes it so that you can extend the index.html css and not overwrite it #}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'coursecatalog/css/course_form.css' %}">
{% endblock css %}

{% block content %}

    <div class="container">

        <div class="page-header">

            <h1 class="larger-h1">
                {% if course_id %}
                    Edit Course
                {% else %}
                    Add Course
                {% endif %}
            </h1>

        </div>


        <div class="row">
            <div class="col-md-6">
                <form method="POST" class="post-form" id="course_form" enctype='multipart/form-data'>
                    {% csrf_token %}

                    {% for field in course_form %}
                        <div class="form-group  {% if field.errors %} has-error{% endif %}">
                            <div class="row">
                                <div class="col-md-3 col-sm-3">
                                    <div class="text-right cf-label-divs">
                                        <label for="{{ course_form.field.id_for_label }}"
                                               class="control-label">{{ field.label }}</label>
                                    </div>
                                </div>
                                <div class="col-md-9 col-sm-9">
                                    {# I don't like doing conditions like this, but I couldn't style the file input any other way. #}
                                    {# My attempts to make it use bootstrap classes failed when using widgets in the forms.py file. #}
                                    {% if field.label != "Art" %}
                                        {{ field }}
                                    {% else %}
                                        <span class="btn btn-primary btn-lg btn-file">
                                            Choose... <input id="{{ field.auto_id }}" name="{{ field.html_name }}"  type="file">
                                        </span>
                                        <span id="file_name">{{ course_form.course_art.value }}</span>
                                    {% endif %}


                                    {% if field.help_text %}
                                        <p>
                                            <small> {{ field.help_text }} </small>
                                        </p>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-offset-3 col-sm-offset-3 col-md-9 col-sm-9">
                                    <div class="text-danger">{{ field.errors.as_text }}</div>
                                </div>
                            </div>

                        </div>
                    {% endfor %}

                    {# Hidden submit btn placed in form. #}
                    <button id="submit-course-form-btn" type="submit" class="hidden">Submit</button>

                </form>

            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                {% if messages %}

                    {# source: https://coderwall.com/p/wekglq/bootstrap-and-django-messages-play-well-together #}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} text-center" role="alert">
                            <strong>{{ message }}</strong></div>
                    {% endfor %}

                {% endif %}
            </div>
            <div class="col-md-2 ">
                <div class="pull-right">
                    {# Using a label here to get around issue w/ submitting a form using a control outside the form. #}
                    {# The only possible issue with it is that this "submit button" cannot be tab selected. #}
                    <label for="submit-course-form-btn" id="submit_btn_label" class="btn btn-primary">Submit</label>
                    {# or <a href="" onClick="window.history.back();return false;">cancel</a>#}
                    or <a href="{{ request.META.HTTP_REFERER }}">cancel</a>
                    <!-- I am assuming that cancel would take you back to where you were before.-->
                </div>
            </div>
        </div>


    </div>
{% endblock content %}


{#The command block.super makes it so that you can append to index.html block javascript but not overwrite it #}
{% block javascript %}
    {{ block.super }}
    <script src="{% static 'coursecatalog/js/course_form.js' %}"></script>
{% endblock javascript %}

templates/coursecatalog/course_list.html
{% extends 'coursecatalog/index.html' %}

<title>{% block title %}Courses{% endblock title %}</title>

{% block content %}

    <div class="container">

        <div class="page-header">

            <h1 class="larger-h1">
                JSU Course Catalog
                {% if course_list %}
                    <p>
                        <small>Please select from our awesome courses!</small>
                    </p>
                {% endif %}
            </h1>

        </div>



        {% if course_list %}

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Course Title</th>
                    <th>Instructor</th>
                    <th>Duration</th>
                </tr>
                </thead>
                <tbody>
                {% for course in course_list %}
                    <tr>
                        <td>{{ course.pk }}</td>
                        <td><a href="{% url 'detail_course' course.id %}">{{ course.title }}</a></td>
                        <td>{{ course.instructor }}</td>
                        {# I found out about get_foo_display after writing my own template filter to solve the display format issue. #}
                        {# <td>{{ course.duration | format_duration_as_week }}</td>  #}
                        {# https://docs.djangoproject.com/en/dev/ref/models/instances/#django.db.models.Model.get_FOO_display #}
                        <td>{{ course.get_duration_display }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        {% else %}
            <div class="alert alert-danger" role="alert">Sadly, no courses are available at this time.</div>
        {% endif %}

    </div>
{% endblock content %}

templates/coursecatalog/index.html
{% load staticfiles %}
{% load custom_template_tags %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>JSU | {% block title %}{% endblock %}</title>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{% block description %}{% endblock %}">

        <meta name="keywords" content="{% block keywords %}{% endblock %}">
        <meta name="author" content="Jared Snider">

        <link rel="shortcut icon" href="{% static 'coursecatalog/img/favicon.ico' %}">
        <link rel="icon" href="{% static 'coursecatalog/img/favicon.ico' %}">

        {% block css %}
            <!-- CSS -->

            <!-- Latest Bootstrap CSS -->
            <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

            <!-- App CSS -->
            <link rel="stylesheet" href="{% static 'coursecatalog/css/index.css' %}">

        {% endblock %}

    </head>

    <body>

        <!-- Navigation -->
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Jared Snider University</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li >
                            <a href="{% url 'course_list' %}">Course Catalog </a>
                        </li>
                        <li>
                            <a href="{% url 'add_course' %}">Add Course</a>
                        </li>
                    </ul>
                </div> <!-- /.navbar-collapse -->
          </div> <!-- /.container-fluid -->
        </nav>



        {% block content %}

            <!-- All child templates that extend index.html will be put here. -->

        {% endblock content  %}

        <!-- Javascript -->
        <!-- Placed at the end of the document so the pages load faster -->
        {% block javascript %}

            <!-- Latest jQuery -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

            <!-- jQuery client side validation plugin - using b/c I don't have time to manually implement my own -->
            <script src="http://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.js"></script>

            <!-- Latest Bootstrap Javascript -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

            <!-- App wide Javascript -->
            <script src="{% static 'coursecatalog/js/index.js' %}"></script>


        {% endblock javascript %}

    </body>

</html>